README.md
pom.xml
src/main/java/org/folio/rest/delegate/System1Delegate.java
src/main/java/org/folio/rest/delegate/ThrowRuntimeErrorDelegate.java
src/main/resources/application.yml
src/test/resources/application.yml

- use latest spring-module-core tenant configuration
- disable camunda-bpm-spring-boot-starter from creating a schema
- create process engine schema for default tenant, 'public'
- update user information, a bit more appropriate
- removed lombok, may consider later if end up with a lot of boiler plate code
We will inevitably be versioning spring-module-core, but for now everything is still new and happens to still be reverse compatible.

Default tenant schema

---

README.md
src/main/java/org/folio/rest/aspect/TenantInjectionDelegateAspect.java

- every delegate will inject tenant into thread safe storage for schema identification
- expects deployment/process to be created with a tenant specified
to improve upon this the create of deployment/process can be intercepted and set the form-data tenant-id from the tenant header, but for now we can just add it to the form data
this has been tested with multiple tenants within Okapi
uses latest commit to spring-module-core, https://github.com/folio-org/spring-module-core/commit/40db15effd470bfc27116a73c6838cfec5a8c817, which is reverse compatible

aspect to inject tenant for schema selection during delegate execution

---

src/main/resources/descriptors/ModuleDescriptor.json

Actions is currently the only interface exposed by mod-workflow. Making this interface required will ensure mod-workflow is deployed to Okapi for the same tenant. This will assist with the hard dependency of mod-camunda requiring mod-workflows temp ActiveMQ broker.

update module descriptor

---

Dockerfile

The Dockerfile uses
`FROM openjdk:11-jre-slim`
as base image. Run apt-get upgrade to upgrade vulnerable packages. This will fix these vulnerabilities:
* zlib/zlib1g Out-of-bounds Write https://nvd.nist.gov/vuln/detail/CVE-2022-37434
* gnutls28/libgnutls30 Double Free https://nvd.nist.gov/vuln/detail/CVE-2022-2509

FOLIO-3565: openjdk image: apt-get upgrade

---

pom.xml

mod-camunda has a commons-text 1.8 maven dependency https://github.com/folio-org/mod-camunda/blob/c1eb47de77a31a9f45bc0a7205e1485b7619a9c1/pom.xml#L267-L271
However, it is not used, and all commons-text versions below 1.10.0 have a Remote Execution vulnerability: https://nvd.nist.gov/vuln/detail/CVE-2022-42889
Task: Remove the unused commons-text dependency to avoid false positive security warning from Snyk and other vulnerability scanners.

FOLIO-3614: Remove unused commons-text 1.8 dependency

---

src/main/java/org/folio/rest/delegate/FileDelegate.java

Implement a suggestion by @julianladisch here:
- https://github.com/folio-org/mod-camunda/pull/82
"Using try-with-resources prevents resource leaks..."

Prevent resource leaks in FileDelegate when using BufferedReader.

---

src/main/java/org/folio/rest/camunda/delegate/EmailDelegate.java
src/main/java/org/folio/rest/camunda/delegate/FtpDelegate.java
src/main/java/org/folio/rest/camunda/delegate/Input.java
src/main/java/org/folio/rest/camunda/delegate/Output.java
src/main/java/org/folio/rest/camunda/delegate/RequestDelegate.java
src/main/java/org/folio/rest/camunda/service/ScriptEngineService.java
src/main/resources/application.yaml

Add `spring.mail.properties.mail.smtp.ssl.checkserveridentity` property.
Set the default to `true` for security.
Different environments may want to override this.
This can be done by changing the boolean to `false` or setting this environment variable like so:
```
SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_CHECKSERVERIDENTITY=false
```
or disable SSL/TLS entirely:
```
SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=false
```
Change `Optional.of()` to `Optional.ofNullable()` to prevent NPEs.

MODCAMUNDA-1: Address problems discovered while testing and reviewing the latest changes.

---

pom.xml
src/main/java/org/folio/rest/camunda/delegate/AbstractDelegate.java
src/main/java/org/folio/rest/camunda/service/BpmnModelFactory.java
src/main/resources/META-INF/bpm-platform.xml
src/main/resources/application-test.yaml
src/main/resources/application.yaml

The bpm xml file appears to not be used anymore.
Remove the bpm xml file.
Add all of the bpm configuration settings to the yaml file with the defaults specified so that it is easier to figure them out.
The use of lombok for logging results in a static class name usage for the log. This doesn't work well for an abstract class.
Instead, instantiate the log in a non-static way so that the implementation class name is used.
Remove the unused `camunda.spring.boot.version` from the `pom.xml` file. Add a common version number setting for the graalvm.
Update the graalvm versions.

MODCAMUNDA-1: BMP related changes, removing dead code and fixing log messages.

---

descriptors/DeploymentDescriptor-template.json
descriptors/ModuleDescriptor-template.json
pom.xml
src/main/resources/openapi.yaml
src/test/resources/application.yaml

Deployment is not working as expected.
This also removes some unused configuration, such as the resource exclusion for descriptors under `src/main/resources` (the descriptors are no longer stored there).
This also makes tests easier to discern by reducing excess logging by default while keeping important logging and by providing more descriptive IDs for the openapi modes.
The more descriptive IDs should make reading the logs to determine what is going on when investigating openapi build problems.

The resource filtering syntax has changed, update the descriptors.

---

src/main/java/org/folio/rest/camunda/service/CamundaApiService.java

Resolves [MODCAMUNDA-9](https://folio-org.atlassian.net/browse/MODCAMUNDA-9)
Setting cascade to true allows for deletion of workflow even when there are incidents.

MODCAMUNDA-9: The delete deployment method should pass true in the cascade parameter.

---

src/main/java/org/folio/rest/camunda/delegate/FileDelegate.java

Introduces changes to:
- Write only target input file for File Delegate.
- Improved File Delegate write operation.

TAMU Sprint 17 into Upstream FOLIO mod-camunda.

---

descriptors/ModuleDescriptor-template.json
src/main/resources/application.yaml

Expose additional notable environment variables in the Module Descriptor. The default settings provided, except for maybe the admin account name and associated passwords, should represent the sane default values for auto-deployment.
The ActiveMQ may be removed in the future but for now it is in use. Expose the settings such that if a non-local ActiveMQ is used, then it can be appropriately configured.
The server port should not change from 8081 during deployment without additional module descriptor changes. Document the server port setting as a practice.
The server context path is also exposed as a practice.
The Flyway should be disabled by default for auto-deployment (in general).
Expose the tenant information to make the required changes more obvious should a non-default tenant be used. …

Improve Module Descriptor and application.yml to favor auto-deployment.

---

descriptors/ModuleDescriptor-template.json
src/main/resources/application.yaml

The mod-camunda is not deploying correctly by default. The console logs state that `CAMUNDA_BPM_DATABASE_SCHEMAUPDATE` might need to be set to `true` or `create-drop`.

The camunda database schema update (CAMUNDA_BPM_DATABASE_SCHEMAUPDATE) likely must be true by default.

---

src/main/resources/application.yaml

The database is set to PostgreSQL by default but the `schema-scripts` are still set to H2. Keep the H2 for easy uncommenting during local development but set the default to PostgreSQL.

Change default schema-scripts from H2 to Postgresql.

---

src/main/java/org/folio/rest/camunda/delegate/AbstractDelegate.java
src/main/java/org/folio/rest/camunda/delegate/AbstractRuntimeDelegate.java
src/main/java/org/folio/rest/camunda/delegate/CompressFileDelegate.java
src/main/java/org/folio/rest/camunda/delegate/DatabaseConnectionDelegate.java
src/main/java/org/folio/rest/camunda/delegate/DatabaseQueryDelegate.java
src/main/java/org/folio/rest/camunda/delegate/EmailDelegate.java
src/main/java/org/folio/rest/camunda/delegate/FileDelegate.java
src/main/java/org/folio/rest/camunda/delegate/FtpDelegate.java
src/main/java/org/folio/rest/camunda/delegate/Input.java
src/main/java/org/folio/rest/camunda/delegate/InputDelegate.java
src/main/java/org/folio/rest/camunda/delegate/Output.java
src/main/java/org/folio/rest/camunda/delegate/ProcessorDelegate.java
src/main/java/org/folio/rest/camunda/delegate/RequestDelegate.java
src/main/java/org/folio/rest/camunda/delegate/SetupDelegate.java
src/main/java/org/folio/rest/camunda/service/BpmnModelFactory.java
src/main/java/org/folio/rest/camunda/service/CamundaApiService.java
src/main/resources/application.yaml
src/test/java/org/folio/rest/camunda/delegate/AbstractDatabaseOutputDelegateTest.java
src/test/java/org/folio/rest/camunda/delegate/AbstractWorkflowIODelegateTest.java
src/test/java/org/folio/rest/camunda/delegate/AbstractWorkflowInputDelegateTest.java
src/test/java/org/folio/rest/camunda/delegate/AbstractWorkflowOutputDelegateTest.java
src/test/java/org/folio/rest/camunda/delegate/ProcessorDelegateTest.java
src/test/java/org/folio/rest/camunda/delegate/SetupDelegateTest.java
src/test/java/org/folio/rest/camunda/service/CamundaApiServiceTest.java
src/test/java/org/folio/rest/camunda/utility/Parameters.java

[MODCAMUNDA-13](https://folio-org.atlassian.net/browse/MODCAMUNDA-13)
This does not yet have the form fields added.
The task has been tested activate, run, and complete without incident.
The project is updated to reflect the Workflow Components changes.
This removes some of the redundant code and relocates it into the abstract class for reducing repeated code.
This also adds support for logging the BPMN on error during activation via: `org.folio.rest.camunda.service.CamundaApiService`.

MODCAMUNDA-13: Get the InputTask working in its most basic form.

---

src/main/java/org/folio/rest/camunda/delegate/FileDelegate.java

[MODCAMUNDA-14](https://folio-org.atlassian.net/browse/MODCAMUNDA-14)
The error described in the ticket relates to a lack of NULL checks while logging a warning. Add a NULL check and make sure the log is printed. Add an addition log specific to the NULL check and update the existing log.
This shows an underlying problem in either the crafted Workflow or some part of the process.
There may be additional work required to fix the cause of the warning.
This only fixes the problem where the warning log itself doesn't generate an error.

MODCAMUNDA-14: Improve the error logging regarding FileTask write problems.

---

src/main/java/org/folio/rest/camunda/controller/WorkflowController.java
src/main/resources/openapi.yaml

Resolves [MODCAMUNDA-3](https://github.com/folio-org/mod-camunda/compare/MODCAMUNDA-3).
These extra paths with a trailing forward-slash `/` (U+002F) should not longer be needed.
The `openapi.xml` file is rebuilt using `mvn clean verify -P openapi`.
There should no longer be any controller endpoints with explicit trailing slashes defined.

MODCAMUNDA-3: Clean up trailing slash work-around.

---

Dockerfile
pom.xml
src/main/resources/openapi.yaml
src/test/java/org/folio/rest/camunda/delegate/FileDelegateTest.java
src/test/resources/application.yaml

Resolves [MODCAMUNDA-21](https://folio-org.atlassian.net/browse/MODCAMUNDA-21)
Switch to JDK21 which has better spring-boot 3.3.x support as well as better GraalVM support.
The `com.jcraft` has migrated to `com.github.mwiede`, so update that and the version.
Update the graalvm related dependencies.
Add the polyglot dependencies.
~The `org.jacoco` `jacoco-maven-plugin` must be upgraded or it will fail with the new spring-boot 3.3.x changes.~
Fix some warnings and change the default `springframework.test` setting.
Remove duplicate dependency in the pom file.
The `-community` edition of the packages should be brought in due to licensing concerns.
Remove the direct dependencies that are already brought in already via the `-community` editions.
Suppress the `graalvm.js` that is brought in from …

MODCAMUNDA-21: Upgrade spring-boot 3.3.7 and graalvm to 24.1.1.

---

pom.xml

Resolves [MODCAMUNDA-24](https://folio-org.atlassian.net/browse/MODCAMUNDA-24)
see: https://cwe.mitre.org/data/definitions/611.html
The `commons-vfs2` has not seen updates in a long time.
This gives reason to add an exclusion and manually add the dependency.

MODCAMUNDA-24: CWE-611: Upgrade hadoop to 3.4.1

---

pom.xml

Resolves [MODCAMUNDA-29](https://folio-org.atlassian.net/browse/MODCAMUNDA-29).
The original request is to upgrade specifically to `21.17.0.0`.
I have discovered that this `ojdbc11` is version managed by `spring-boot`. Let `spring-boot` manage this version.

MODCAMUNDA-29: Upgrade from ojdbc10 to ojdbc11.

---

src/test/java/org/folio/rest/camunda/controller/WorkflowControllerTest.java
src/test/java/org/folio/rest/camunda/kafka/EventConsumerTest.java

Resolves [MODCAMUNDA-26](https://folio-org.atlassian.net/browse/MODCAMUNDA-26).
Replace `@MockBean` and `@SpyBean`.
- `@MockitoBean` and `MockitoSpyBean` are the replacemenets to the deprecated or removed `@MockBean` and `@SpyBean`.
Address failing bean problems.
- The `ObjectMapper` bean is provided because the `@MockitoSpyBean` no longer instantiates when there is no bean found in the way that no available or deprecated `@SpyBean` does.
- see: https://github.com/spring-projects/spring-framework/issues/33935
This requires the changes from [Spring Module Core PR 74](https://github.com/folio-org/spring-module-core/pull/74) for [SPRNGCORE-6](https://folio-org.atlassian.net/browse/SPRNGCORE-6).

MODCAMUNDA-26: Make compatible with spring-boot 3.4 upgrades.

---

README.md

Resolves [MODCAMUNDA-22](https://folio-org.atlassian.net/browse/MODCAMUNDA-22).
Remove a lot of old information or information that would potentially require constant updating. In cases of constant updating, remove explicit versions or directly link to the source files.
Add build and run documentation.
Remove all of the old vagrant related information. This ha long since been deprecated and is no longer supported in the FOLIO community, in general.
Fix links as appropriate.
Update the copyright year.

MODCAMUNDA-22: Update the read me documentation.

---

pom.xml

- [MODCAMUNDA-37](https://folio-org.atlassian.net/browse/MODCAMUNDA-37)
- [MODCAMUNDA-38](https://folio-org.atlassian.net/browse/MODCAMUNDA-38)
- [MODCAMUNDA-39](https://folio-org.atlassian.net/browse/MODCAMUNDA-39)
- [MODCAMUNDA-40](https://folio-org.atlassian.net/browse/MODCAMUNDA-40)
- [MODCAMUNDA-41](https://folio-org.atlassian.net/browse/MODCAMUNDA-41)
- [MODCAMUNDA-42](https://folio-org.atlassian.net/browse/MODCAMUNDA-42)
- [MODCAMUNDA-43](https://folio-org.atlassian.net/browse/MODCAMUNDA-43)
- [MODCAMUNDA-44](https://folio-org.atlassian.net/browse/MODCAMUNDA-44)
Note that `7.23.0` of `camunda` causes compilation failure and is not upgraded at this time. Even `7.22.0` has problems.
This is the test failure from attempting to upgrade to `7.22.0` of camunda:
```
[ERROR] …
```

Bump versions of numerous explicit dependencies.
